format: 
  revealjs: 
    theme: custom.scss
    incremental: true
    title-slide-attributes:
      data-background-color: "#533146"
      data-color: "#EDEEF"
    slide-number: c/t
    show-slide-number: all
    menu: false
    
execute: 
  echo: true
  warning: false
  message: false
  dev: "ragg_png"
  dpi: 320
  out.width: "80%"
  fig.width: 6
  fig.asp: 0.618
  fig.retina: 2
  fig.align: "center"
  fig.show: "hold"
  
footer: "Slides by [Dr. Lucy D'Agostino McGowan](https://lucymcgowan.com)"